version: '2'
services:

  wordpress:
    #image: wordpress
    build:
      context: ./
      dockerfile: Dockerfile-wordpress
    ports:
      - 9090:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./test:/tmp/test

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example

